apiVersion: v1
kind: Service
metadata:
  name: staging-loadbalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: udacity.project.vahiwe.com
spec:
  type: LoadBalancer
  selector:
    app: staging
  ports:
    - port: 80
      targetPort: 80